#!/bin/bash
#
#
#
PROG=$0
PRIVATE_CONF=/home/portex/portex_ecm.d/tnlctl/conf/custom.conf

if [ -f $PRIVATE_CONF ]; then
  echo "Use private"
  TARGET_HOST=$(egrep "^REG_SERVER_HOST" /home/portex/portex_ecm.d/tnlctl/conf/custom.conf | awk -F= '{print $2}')
else
  echo "Use public"
  TARGET_HOST=$(egrep "^REG_SERVER_HOST" /home/portex/portex_ecm.d/tnlctl/conf/tnlctl.conf | awk -F= '{print $2}')

fi
echo "Target host is" $TARGET_HOST

while true; do

  date
  PTL=$(/bin/nc -zv -w 3 $TARGET_HOST 80 2>&1 | egrep "succeeded!")
  if [[ "$PTL" == "$LPTL" ]]; then
    echo "MCS Cloud control-channel status is not changed; status is $LPTL"
  elif [[ $PTL ]]; then
    echo "MCS Cloud control-channel is available"
    echo -e "red_off\c" | nc -q 1 -U /var/run/uds_led
    LPTL=$PTL
  else
    echo "MCS Cloud control-channel is NOT available"
    echo -e "red_on\c" | nc -q 1 -U /var/run/uds_led
    LPTL=$PTL
  fi

  echo ""

  sleep 5
done
