#!/bin/bash
#
#    Note: postinstall of tnlctl tool set script for dpkg
#
#Revision:2018110401
#
#

# setup client ssh config
echo "setup client ssh config for tnlctl..."
mkdir -p /root/.ssh
touch /root/.ssh/config
echo "ServerAliveInterval 30" >> /root/.ssh/config
echo "ServerAliveCountMax 60" >> /root/.ssh/config
chmod 600 /root/.ssh/config
echo "done."

# adduser
/tmp/tnlctl/adduser.sh

# copy scripts
echo "copy scripts to target folder..."
cat /tmp/tnlctl/ssmenu     > ~ssuser/ssmenu
cat /tmp/tnlctl/sscom      > ~ssuser/sscom
cat /tmp/tnlctl/sscomsub   > ~ssuser/sscomsub
cat /tmp/tnlctl/sscomsetup > ~ssuser/sscomsetup
cat /tmp/tnlctl/ssattached > ~ssuser/ssattached
cat /tmp/tnlctl/ssmods     > ~ssuser/ssmods
chown ssuser:ssuser ~ssuser/ssmenu
chown ssuser:ssuser ~ssuser/sscom*
chown ssuser:ssuser ~ssuser/ssattached
chown ssuser:ssuser ~ssuser/ssmods
chmod a+x ~ssuser/ssmenu
chmod a+x ~ssuser/sscom*
chmod a+x ~ssuser/ssattached
chmod a+x ~ssuser/ssmods
echo "done."

# copy config (for minicom)
echo "copy dot files..."
echo "... minicom part ..."
cat /tmp/tnlctl/dot.minirc.dfl > ~ssuser/.minirc.USB0
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB1/' > ~ssuser/.minirc.USB1
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB2/' > ~ssuser/.minirc.USB2
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB3/' > ~ssuser/.minirc.USB3
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB4/' > ~ssuser/.minirc.USB4
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB5/' > ~ssuser/.minirc.USB5
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB6/' > ~ssuser/.minirc.USB6
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB7/' > ~ssuser/.minirc.USB7
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB8/' > ~ssuser/.minirc.USB8
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB9/' > ~ssuser/.minirc.USB9
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB10/' > ~ssuser/.minirc.USB10
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB11/' > ~ssuser/.minirc.USB11
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB12/' > ~ssuser/.minirc.USB12
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB13/' > ~ssuser/.minirc.USB13
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB14/' > ~ssuser/.minirc.USB14
cat /tmp/tnlctl/dot.minirc.dfl | sed 's/USB0/USB15/' > ~ssuser/.minirc.USB15
chown ssuser:ssuser ~ssuser/.minirc.USB*
echo "... bash part ..."
# backup first
cat ~ssuser/.bashrc > ~ssuser/.bashrc-BAK
cat /tmp/tnlctl/dot.bashrc > ~ssuser/.bashrc
echo "done."

rm -rf /tmp/tnlctl/

