#!/bin/bash
#
#Revision:2018101601
#

export PATH=/sbin:${PATH}

INPUT=/tmp/ssattached-input.$$
OUTPUT=/tmp/ssattached-output.$$

# trap and delete temp files
trap "rm $OUTPUT; rm $INPUT; exit" SIGHUP SIGINT SIGTERM

#
# Purpose - display output using msgbox
#  $1 -> set msgbox height
#  $2 -> set msgbox width
#  $3 -> set msgbox title
#
function display_output(){
    local h=${1-10}        # box height default 10
    local w=${2-41}        # box width default 41
    local t=${3-Output}    # box title
    dialog --backtitle "SS Menu Output" --title "${t}" --clear --msgbox "$(<$OUTPUT)" ${h} ${w}
}
#
# Purpose - display a system info
#
function show_attached_session(){
    screen -list | grep Shared | awk -F. '{print $1}' > $OUTPUT
    display_output 20 80 "Current attached session(es)"
}
#
# set infinite loop
#
while true
do
    screen -list | grep Shared | awk '{print $1}' | awk -F. '{print $1,"attach_to_"$1}' > $OUTPUT

    ### display main menu ###
    dialog --clear  --help-button --backtitle "MCSC SS ATTACHED SESSION(ES)" \
    --title "[ ATTACHED SESSION(ES) - CONSOLE ]" \
    --timeout 300 \
    --menu "Choose the TASK" 20 50 12 \
        "Attached" "Displays Attached Session(es)" \
        $(<"${OUTPUT}") \
        Exit "Exit to Main Menu" 2>"${INPUT}"

        _status=$?
        if [ ${_status} -eq 255 ]
        then
            # dialog timeout
            exit 0
        fi

    menuitem=$(<"${INPUT}")

    # make decsion
    case $menuitem in
        "Exit") exit 0;;
        "Attached") show_attached_session;;
        *) screen -wipe; screen -x ${menuitem}.Shared -s /bin/bash;;
    esac

done

# if temp files found, delete em
[ -f $OUTPUT ] && rm $OUTPUT
[ -f $INPUT ] && rm $INPUT

