#!/bin/bash
#
#Revision:2018110701
#

REV="2018110701"

export PATH=/sbin:${PATH}

INPUT=/tmp/ssmenu-input.$$
OUTPUT=/tmp/ssmenu-output.$$

# get text editor or fall back to vi_editor
vi_editor=${EDITOR-vi}

# trap and delete temp files
trap "rm $OUTPUT; rm $INPUT; exit" SIGHUP SIGINT SIGTERM

#
# Purpose - display output using msgbox
#  $1 -> set msgbox height
#  $2 -> set msgbox width
#  $3 -> set msgbox title
#
function display_output(){
    local h=${1-10}        # box height default 10
    local w=${2-41}        # box width default 41
    local t=${3-Output}    # box title
    dialog --backtitle "SS Menu Output" --title "${t}" --clear --msgbox "$(<$OUTPUT)" ${h} ${w}
}
#
# Purpose - display a system info
#
function show_sysinfo(){
    #tty >$OUTPUT
    #ls -al /dev/pts/* >>$OUTPUT
    cat /dev/null >$OUTPUT
    ifconfig | grep -A 10 wlan0 | grep ether | awk '{print $2}' >>$OUTPUT
    grep ^Serial /proc/cpuinfo | awk '{print $3}' >>$OUTPUT
    display_output 13 25 "System Info"
}
#
# set infinite loop
#
while true
do

    ### display main menu ###
    dialog --clear  --help-button --backtitle "MCSC SS rev:${REV}" \
    --timeout 1800 \
    --title "[ M A I N - M E N U ]" \
    --menu "You can use the UP/DOWN arrow keys, the first \n\
    letter of the choice as a hot key, or the \n\
    number keys 1-9 to choose an option.\n\
    Choose the TASK" 24 50 10 \
        "System Info" "Displays System Info" \
        "USB Console" "Go to USB Ports Consloe" \
        Editor "Start a text editor" \
        Shell "Open a shell" \
        "New Session" "Create a shared session" \
        "Join Session" "Join to a shared session" \
        Modules "Enter Sub Menu of Modules" \
        Exit "Exit/Logout" 2>"${INPUT}"

    _status=$?
    if [ ${_status} -eq 255 ]
    then
        # dialog timeout
        exit 0
    fi

    menuitem=$(<"${INPUT}")

    # make decision
    case $menuitem in
        "System Info") show_sysinfo;;
        "USB Console") /home/ssuser/sscom;;
        Editor) $vi_editor;;
        "New Session") screen -wipe; screen -S Shared -s /bin/bash;;
        "Join Session") /home/ssuser/ssattached;;
        Shell) bash;;
        Modules) ./ssmods;;
        Exit) echo "Bye"; break;;
    esac

done

# if temp files found, delete em
[ -f $OUTPUT ] && rm $OUTPUT
[ -f $INPUT ] && rm $INPUT

